[workspace]
members = [
    "aura",
    "pgp-ui/src-tauri"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.103"
argon2 = "0.6.0"
arti-client = { version = "0.47.0", features = ["pt-client", "onion-service-service"] }
chacha20poly1305 = "0.11.0"
hex = "0.4.3"
keepass = "=0.13.10"
futures = "0.3"
libp2p = { version = "0.57.0", features = ["tokio", "macros", "kad", "ping", "identify", "noise", "yamux"] }
log = "0.4"
rand = "0.8.5"
rusqlite = { version = "0.40.2", features = ["bundled"] }
sequoia-openpgp = { version = "2.3.0", default-features = false, features = ["crypto-cng"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
tauri = "2.9.5"
tauri-build = "2.5.3"
tauri-plugin-log = "2"
tokio = { version = "1.53.2", features = ["full"] }
tor-hsservice = "0.47.0"
tor-rtcompat = "0.47.0"
windows-sys = { version = "0.61.2", features = ["Win32_System_Diagnostics_Debug", "Win32_System_Threading"] }
zeroize = { version = "1.9.0", features = ["derive"] }
